export const beddingproducts = [
  {
    title: "pillow",
    category: "pillow",
    desc: "description daadadassdsd",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "blanket",
    category: "blanket",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "pool towel",
    category: "bath",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "bed sheet",
    category: "coverlets",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Duvet Cover",
    category: "duvets",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Hand Towel",
    category: "bath",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Duvet",
    category: "duvets",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Pillow Cover",
    category: "pillow case",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "blanket",
    category: "blankets",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
];

export const bathproducts = [
  {
    title: "bath towel",
    category: "bath",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "pillow",
    category: "hotel bedding",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "blanket",
    category: "hotel bedding",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "pool towel",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "bed sheet",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Duvet Cover",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Hand Towel",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Duvet",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Pillow Cover",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "blanket",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
];

const mainhotelcat = [
  "Bedspreads",
  "Blankets",
  "Contract Bedding",
  "Coverlets",
  "Duvets",
  "Hotel Bed Linen",
  "Hotel Bed Scarf",
  "Hotel Mattress Pads",
  "Hotel Pillows",
  "mattress Encasements",
  "Pillow Case",
];

export const featurecategories = [
  { cat: "Bedspreads", imgurl: "./assets/categories/bedding.png" },
  { cat: "Blabkets", imgurl: "./assets/categories/bedding.png" },
  { cat: "Coverlets", imgurl: "./assets/categories/bedding.png" },
  { cat: "Duvets", imgurl: "./assets/categories/bedding.png" },
  { cat: "Hotel Bed Linen", imgurl: "./assets/categories/bedding.png" },
  { cat: "Hotel Mattress Pads", imgurl: "./assets/categories/bedding.png" },
  { cat: "Hotel Pillows", imgurl: "./assets/categories/bedding.png" },
  { cat: "Salt Lamp", imgurl: "./assets/categories/bedding.png" },
];
