export const beddingproducts = [
  {
    title: "pillow",
    category: "pillow",
    desc: "description daadadassdsd",
    measurement: "",
    imgurl: "./assets/hotel/pillow.jpg",
  },
  {
    title: "blanket",
    category: "blanket",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/.jpg",
  },
  {
    title: "pool towel",
    category: "bath",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/towels.jpg",
  },
  {
    title: "bed sheet",
    category: "coverlets",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/bedspread.jpg",
  },
  {
    title: "Duvet Cover",
    category: "duvets",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/duvets.jpg",
  },
  {
    title: "Hand Towel",
    category: "bath",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/handtowel.jpg",
  },
  {
    title: "Duvet",
    category: "duvets",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/duvets.jpg",
  },
  {
    title: "Pillow Cover",
    category: "pillow case",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/pillowcase.jpg",
  },
  {
    title: "blanket",
    category: "blankets",
    desc: "description",
    measurement: "",
    imgurl: "./assets/hotel/blanket.jpg",
  },
];

export const bathproducts = [
  {
    title: "bath towel",
    category: "bath",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "pillow",
    category: "hotel bedding",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "blanket",
    category: "hotel bedding",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "pool towel",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "bed sheet",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Duvet Cover",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Hand Towel",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Duvet",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "Pillow Cover",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
  {
    title: "blanket",
    category: "hotel",
    desc: "description",
    measurement: "",
    imgurl: "./hotel/bedding/towel.jpg",
  },
];

const mainhotelcat = [
  "Bedspreads",
  "Blankets",
  "Contract Bedding",
  "Coverlets",
  "Duvets",
  "Hotel Bed Linen",
  "Hotel Bed Scarf",
  "Hotel Mattress Pads",
  "Hotel Pillows",
  "mattress Encasements",
  "Pillow Case",
];

// export const featurecategories = [
//   { cat: "Bedspreads", imgurl: "./assets/categories/silverbedspread.jpg" },
//   { cat: "Blankets", imgurl: "./assets/categories/blanket.jpg" },
//   { cat: "Coverlets", imgurl: "./assets/categories/coverlet.jpg" },
//   { cat: "Duvets", imgurl: "./assets/categories/duvets.jpg" },
//   { cat: "Bed Linen", imgurl: "./assets/categories/bedsheetset.jpg" },
//   { cat: "Mattress Pad", imgurl: "./assets/categories/mattresspad.jpg" },
//   { cat: "Pillows", imgurl: "./assets/categories/pillow.jpg" },
//   { cat: "Bath", imgurl: "./assets/categories/bathroomcurtains.jpg" },
// ];

export const featurecategories = [
  {
    cat: "Contract Bedding",
    imgurl: "./assets/categories/BedScarves.jpg",
    catid: "contractbedding",
  },
  {
    cat: "Bedspreads",
    imgurl: "./assets/categories/silverbedspread.jpg",
    catid: "bedspreads",
  },
  {
    cat: "Blankets",
    imgurl: "./assets/categories/blanket.jpg",
    catid: "blankets",
  },
  {
    cat: "Coverlets",
    imgurl: "./assets/categories/coverlet.jpg",
    catid: "coverlets",
  },
  { cat: "Duvets", imgurl: "./assets/categories/duvets.jpg", catid: "duvets" },
  {
    cat: "Bed Linen",
    imgurl: "./assets/categories/bedsheetset.jpg",
    catid: "bedlinen",
  },
  {
    cat: "Mattress Pad",
    imgurl: "./assets/categories/mattresspad.jpg",
    catid: "mattresspad",
  },
  {
    cat: "Pillows",
    imgurl: "./assets/categories/pillow.jpg",
    catid: "pillows",
  },
  {
    cat: "Bath",
    imgurl: "./assets/categories/bathroomcurtains.jpg",
    catid: "bath",
  },
];

export const bedding = [
  {
    catid: "bedlinen",
    title: "Pillow",
    category: "pillow",
    desc: "white color pillow for bedroom",
    measurement: "",
    imgurl: "assets/hotel/pillow.jpg",
  },
  {
    catid: "bedlinen",
    title: "Pillow Case",
    category: "pillow case",
    desc: "pillow case for pillow",
    measurement: "",
    imgurl: "assets/hotel/pillowcase.jpg",
  },
  {
    catid: "bedlinen",
    title: "Silk Pillow Case",
    category: "pillow case",
    desc: "white silk pillow case for pillow",
    measurement: "",
    imgurl: "assets/hotel/pillowcase2.jpg",
  },
  {
    catid: "bedlinen",
    title: "Bath Curtains",
    category: "bath",
    desc: "curtains for bath",
    measurement: "",
    imgurl: "assets/hotel/bathcurtains.jpg",
  },
  {
    catid: "bedlinen",
    title: "White Bath Curtians",
    category: "bath",
    desc: "Curtains for bathroom white color",
    measurement: "",
    imgurl: "assets/hotel/bathroomcurtains.jpg",
  },
  {
    catid: "bedlinen",
    title: "Bath Towel",
    category: "bath",
    desc: "towel for bathroom use",
    measurement: "",
    imgurl: "assets/hotel/bathtowel.jpg",
  },
  {
    catid: "bedlinen",
    title: "White Bath Towel",
    category: "bath",
    desc: "towel for bathroom use",
    measurement: "",
    imgurl: "assets/hotel/bathtowel2.jpg",
  },
  {
    catid: "bedlinen",
    title: "Bed Base",
    category: "furniture",
    desc: "wooden base for bed",
    measurement: "",
    imgurl: "assets/hotel/bedbase.jpg",
  },
  {
    catid: "bedlinen",
    title: "Colored Bed Scarf",
    category: "bed scarf",
    desc: "colored scarf for bed",
    measurement: "",
    imgurl: "assets/hotel/bedscarves.jpg",
  },
  {
    catid: "bedlinen",
    title: "Bed Scarf",
    category: "bed scarf",
    desc: "scarf for bed",
    measurement: "",
    imgurl: "assets/hotel/bedscarves2.jpg",
  },
  {
    catid: "bedlinen",
    title: "White Bed Sheet Set",
    category: "Bed Linen",
    desc: "white color sheet set for bed",
    measurement: "",
    imgurl: "assets/hotel/flatwhitebedsheet.jpg",
  },
  {
    catid: "bedlinen",
    title: "White Bed Sheet Set",
    category: "Bed Linen",
    desc: "white color sheet set for bed",
    measurement: "",
    imgurl: "assets/hotel/bedScarves2.jpg",
  },
];

export const contractbedding = [
  {
    catid: "bedlinen",
    title: "White Bed Sheet Set",
    category: "Bed Linen",
    desc: "white color sheet set for bed",
    measurement: "",
    imgurl: "flatwhitebedsheet.jpg",
  },
  {
    catid: "bedlinen",
    title: "White Bed Sheet Set",
    category: "Bed Linen",
    desc: "white color sheet set for bed",
    measurement: "",
    imgurl: "bedScarves2.jpg",
  },
  {
    catid: "bedlinen",
    title: "Colored Bed Scarf",
    category: "bed scarf",
    desc: "colored scarf for bed",
    measurement: "",
    imgurl: "bedscarves.jpg",
  },
  {
    catid: "bedlinen",
    title: "Bed Scarf",
    category: "bed scarf",
    desc: "scarf for bed",
    measurement: "",
    imgurl: "bedscarves2.jpg",
  },
];
export const bedlinen = [
  {
    catid: "bedlinen",
    title: "White Bed Sheet Set",
    category: "Bed Linen",
    desc: "white color sheet set for bed",
    measurement: "",
    imgurl: "assets/hotel/flatwhitebedsheet.jpg",
  },
  {
    catid: "bedlinen",
    title: "White Bed Sheet Set",
    category: "Bed Linen",
    desc: "white color sheet set for bed",
    measurement: "",
    imgurl: "assets/hotel/bedScarves2.jpg",
  },
  {
    catid: "bedlinen",
    title: "Colored Bed Scarf",
    category: "bed scarf",
    desc: "colored scarf for bed",
    measurement: "",
    imgurl: "assets/hotel/bedscarves.jpg",
  },
  {
    catid: "bedlinen",
    title: "Bed Scarf",
    category: "bed scarf",
    desc: "scarf for bed",
    measurement: "",
    imgurl: "assets/hotel/bedscarves2.jpg",
  },
];
